version: '3.1'

services:

  hotel_db:
    image: postgres
    container_name: hotel_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hotel_db
    ports:
      - 5432:5432